### ISSUE TITLE
W10, .bin & .param needs to be in .exe directory

### ISSUE THREAD

**Issue by Madsfoto** [nihui/dain-ncnn-vulkan#2]
If the .bin and .param files are not in the same directory than the .exe , then 

> fopen depthnet.param failed (And the same for the rest of the files)

User solution: Move the files to the .exe directory. 
Long term solution: Have dain-ncnn-vulcan look in the _best_ directory

**Comment by BahzBeih** [comment]
I got the same error too, I fixed it by copying all files on "best" folder to the .exe directory.

**Comment by TheJokingTeen** [comment]
What do you mean move them to the .exe directory? Do you mean folder /dain-ncnn-vulkan/ bc that has the executable in it? Tried that, but didn't work...

**Comment by Madsfoto** [comment]
> What do you mean move them to the .exe directory? Do you mean folder /dain-ncnn-vulkan/ bc that has the executable in it? Tried that, but didn't work...

On the newest download it's no longer required to move the bin and maram files.

**Comment by Mar2ck** [comment]
Newest download? There hasn't been an update since september and the issue is still there aswell as cain-ncnn and rife-ncnn

**Comment by Madsfoto** [comment]
> Newest download? There hasn't been an update since september and the issue is still there aswell as cain-ncnn and rife-ncnn

1) I know. What I'm saying is that when you download the artifacts now [https://github.com/nihui/dain-ncnn-vulkan/actions/runs/340225105 ], running a cmd with **dain-ncnn-vulkan.exe -i in -o Out** (with source files in the folder in, and output in out) works. 

2) I know :)
The other have not incorporated the patch from PumpkinCheshire, so that's why it doesn't work right away.


I'm not a developer, I can only say how things are.

**Comment by Mar2ck** [comment]
Ah i see, the pull request has an action build despite not being merged. Fair enough
